version: "3"
services:
  web:
    environment:
       - LC_ALL=C.UTF-8
       - LANG=C.UTF-8
       - FLASK_DEBUG=True
       - FLASK_APP=swagger_stub_api
    env_file: .env
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/code
    command: /bin/bash -c "python3 swagger_stub_api/run.py"
