version: "3"
services:
  web:
    environment:
       - LC_ALL=C.UTF-8
       - LANG=C.UTF-8
       - FLASK_DEBUG=True
       - FLASK_APP=app.py
       - SWAGGER_PATH=./swagger.yaml
    env_file: .env
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/code
    command: /bin/bash -c "flask run --host=0.0.0.0 --port=3000"
